spring.application.name=Clinic_Skin_BE

 # Port
server.port=1209

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/hopital_care?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1209
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

# JWT c?u hình
jwt.secret=keyJWT2025
jwt.expiration=86400000
# 1 ngày (1 * 24 * 60 * 60 * 1000 ms)

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


# Logging
logging.level.org.springframework.security=DEBUG
logging.level.root=DEBUG

# Encoding + TimeZone (tu? ch?n nh?ng nên có)
spring.jackson.time-zone=Asia/Ho_Chi_Minh
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true


# Show l?i chi ti?t khi dev
server.error.include-message=always
server.error.include-binding-errors=always

#Cloudinary
cloud_name =dk6vu2mlh
api_key =157826111219952
api_secret =KZFXu-d7Tp9vuZOfQA-CXjkapdk

#Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=testDuAnBenhVien@gmail.com
spring.mail.password=nbxpkfqfbcafqwij
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=false


GOOGLE_CLIENT_ID=657783736652-pa9em9g45rp7kpi1vdkgka378fd5vv15.apps.googleusercontent.com

timedatectl set-timezone UTC
ntpdate time.google.com


